<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Activite par villes</title>
<FORM method="post" action="fin_extract_act.php"> 
<SELECT id="select_city" name="Villes" size="1">
<option value='8'>ASKIA</option>
<option value='9'>BAWADA DAJI</option>
<option value='10'>FAYA</option>
<option value='11'>GOUGUI</option>
<option value='12'>GUIZARA</option>
<option value='13'>KOUKOKI</option>
<option value='14'>LOUGOU</option>
<option value='15'>TANI I</option>
<option value='16'>TOUGANA</option>
<option value='17'>BAWADA GUIDA</option>
<option value='18'>GOUBEY</option>
<option value='19'>KAMREY ARAWA</option>
<option value='20'>KAMREY I</option>
<option value='21'>KOLMEY</option>
<option value='22'>MARAKE ROGO</option>
<option value='23'>ANGOUAL KASSA</option>
<option value='24'>BARE BARI</option>
<option value='25'>BAWADA SANKE</option>
<option value='26'>BAYAN DOUTCHI</option>
<option value='27'>BINGUIRA</option>
<option value='28'>BOURTOU</option>
<option value='29'>CHANONO</option>
<option value='30'>DADIN KOWA</option>
<option value='31'>DAN GAO</option>
<option value='32'>DAN KASSARI</option>
<option value='33'>DAN ZOURE I</option>
<option value='34'>Dan-toudou Goumandey</option>
<option value='35'>DANGARI</option>
<option value='36'>DANKEDA</option>
<option value='37'>DAREY GOUGUI</option>
<option value='38'>DOGON TAPKI</option>
<option value='39'>DOUNFOUMAWA</option>
<option value='40'>DOUZOU I</option>
<option value='41'>DOUZOU II</option>
<option value='42'>ERGUEZA (GARINE)</option>
<option value='43'>FANNA I</option>
<option value='44'>FAREY</option>
<option value='45'>GANNA</option>
<option value='46'>GARIN AGOUR</option>
<option value='47'>GARIN ARAWA</option>
<option value='48'>GARIN BAWA</option>
<option value='49'>GARIN DE</option>
<option value='50'>GARIN GABASS</option>
<option value='51'>GARIN MAKERA</option>
<option value='52'>GARIN MALAM</option>
<option value='53'>GARIN MAOUDE</option>
<option value='54'>GARIN TAMA</option>
<option value='55'>GARIN YAMMA</option>
<option value='56'>Garin-dan-zomo</option>
<option value='57'>Garin-maiyodo</option>
<option value='58'>GIGALAWA</option>
<option value='59'>GOFAWA</option>
<option value='60'>GOHO</option>
<option value='61'>GOUANI</option>
<option value='62'>GOUBEY DANGARI</option>
<option value='63'>GOULBI</option>
<option value='64'>GOULMOUNY</option>
<option value='65'>Houda Massari</option>
<option value='66'>ILLELA</option>
<option value='67'>JARKASSA</option>
<option value='68'>JIRGA</option>
<option value='69'>KADANDAME</option>
<option value='70'>KALGO</option>
<option value='71'>Kalgo Zounzourma</option>
<option value='72'>KAOURA LAHAMA</option>
<option value='73'>KARKI MALAN</option>
<option value='74'>KARKI PEULH</option>
<option value='75'>KASSAOURA</option>
<option value='76'>KAWADATA</option>
<option value='77'>KODAP</option>
<option value='78'>KOLFA II</option>
<option value='79'>KOLMEY PEULH</option>
<option value='80'>KORE GABASS</option>
<option value='81'>KORONGOMEY</option>
<option value='82'>KORONGOMEY PEULH</option>
<option value='83'>Kouka-dim aire Matankari pop Dankassari</option>
<option value='84'>KOUMAY</option>
<option value='85'>KOUMTCHI</option>
<option value='86'>KOUZAK</option>
<option value='87'>LILLATO KOKARE</option>
<option value='88'>MAILO</option>
<option value='89'>MARAKE TOUDOU</option>
<option value='90'>MATANGARAY</option>
<option value='91'>MOULLELE I</option>
<option value='92'>NAKI GAZA DETCHI</option>
<option value='93'>NAKI GAZA SARKIN ROUAFI</option>
<option value='94'>ROUDA GOUMANDEY</option>
<option value='95'>ROUKOUTOU</option>
<option value='96'>SABON GARI</option>
<option value='97'>Sabon-garin-zounzourma</option>
<option value='98'>SAOURIN KAIHI</option>
<option value='99'>Saran-allah</option>
<option value='100'>SITRATE BARGOUNAWA</option>
<option value='101'>TABALA I (GARIN NAMATA)</option>
<option value='102'>TABALA IV</option>
<option value='103'>TCHERANOU I</option>
<option value='104'>TCHERANOU II</option>
<option value='105'>TCHITO DJINBANAWA</option>
<option value='106'>TCHITO SARKIN ROUAHI</option>
<option value='107'>TOUDOU</option>
<option value='108'>TOUDOU BAREBARI</option>
<option value='109'>TOUNZOURAWA I</option>
<option value='110'>TSABA ABOULA</option>
<option value='111'>TSABA GARIN MALI</option>
<option value='112'>TSABATANKARI</option>
<option value='113'>YASSEDJI /BABAN KORE PEULH</option>
<option value='114'>YAZOUZOU</option>
<option value='115'>ZAOURAN ZOMO</option>
<option value='116'>ZOUNZOURMA/GARIN</option>
</SELECT> 
<input type="submit" value="VALIDER"> 
</FORM>
